<?php

namespace FacturaScripts\Plugins\Contratos\Controller;

use FacturaScripts\Core\Lib\ExtendedController\EditController;
use FacturaScripts\Core\Tools;
use FacturaScripts\Plugins\Contratos\Model\ContratoServicio;

class EditContratoServicio extends EditController
{

    public function getModelClassName(): string
    {
        return "ContratoServicio";
    }

    public function getPageData(): array
    {
        $data = parent::getPageData();
        $data["title"] = "Contrato";
        $data["icon"] = "fa-solid fa-search";
        return $data;
    }

    public function createViews(): void
    {
        parent::createViews(); // TODO: Change the autogenerated stub
    }


    protected function execPreviousAction($action): bool
    {
        if ($action === 'renew') {
            $this->renewAction();
            return true;
        }

        return parent::execPreviousAction($action);
    }

    protected function loadData($viewName, $view)
    {
        $mvn = $this->getMainViewName();

        switch ($viewName) {
            case $mvn:
                parent::loadData($viewName, $view);
                if (false === $view->model->exists()) {
                    break;
                }

                if ($view->model->suspendido === false) {
                    $this->addButton('EditContratoServicio', [
                        'action' => 'renew',
                        'icon' => 'fa-solid fa-plus',
                        'label' => 'Renovar y generar factura',
                        'type' => 'modal',
                        'color' => 'info'
                    ]);
                }
                break;
        }
    }

    /**
     * Función para renovar el servicio, crea la factura y actualiza el contrato.
     */
    private function renewAction(): void
    {
        if (!$this->request->query->get('code')) {
            Tools::log()->error('No hay contrato para renovar.');
            return;
        }

        if (!$this->request->request->get('date')) {
            Tools::log()->error('No has seleccionado una fecha para la factura');
            return;
        }

        $contrato = new ContratoServicio();
        $contrato->load($this->request->query->get('code'));

        if ($contrato->hasErrorsToRenew()) {
            Tools::log()->error('No se ha renovado el contrato, por favor soluciona las incidencias y vuelve a intentarlo');
            return;
        }


        $res = $contrato->renewService($this->request->request->get('date'));

        switch ($res['status']) {
            case 'error':
                Tools::log()->error($res['message']);
                break;

            case 'ok':
                Tools::log()->notice($res['message']);
                break;
        }
    }
}
